package com.example.marvelapi30.model

object MarvelDb {

    fun getAllCharacters() = listOf<Characters>(
        Characters("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Characters("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Characters("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Characters("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Characters("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
        Characters("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Characters("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Characters("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Characters("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Characters("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
    )

    fun getAllComics() = listOf<Comics>(
        Comics("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Comics("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Comics("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Comics("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Comics("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
        Comics("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Comics("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Comics("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Comics("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Comics("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
    )

    fun getAllSeries() = listOf<Series>(
        Series("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Series("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Series("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Series("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Series("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
        Series("Hulk", "Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets. ",
            "http://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0.jpg"),
        Series("Jessica Jones", "",
            "http://i.annihil.us/u/prod/marvel/i/mg/d/00/5390e41260345.jpg"),
        Series("Wolverine", "Born with super-human senses and the power to heal from almost any wound, Wolverine was captured by a secret Canadian organization and given an unbreakable skeleton and claws. Treated like an animal, it took years for him to control himself. Now, he's a premiere member of both the X-Men and the Avengers.",
            "http://i.annihil.us/u/prod/marvel/i/mg/2/60/537bcaef0f6cf.jpg"),
        Series("Iron Man", "Wounded, captured and forced to build a weapon by his enemies, billionaire industrialist Tony Stark instead created an advanced suit of armor to save his life and escape captivity. Now with a new outlook on life, Tony uses his money and intelligence to make the world a safer, better place as Iron Man.",
            "http://i.annihil.us/u/prod/marvel/i/mg/9/c0/527bb7b37ff55.jpg"),
        Series("Captain America", "Vowing to serve his country any way he could, young Steve Rogers took the super soldier serum to become America's one-man army. Fighting for the red, white and blue for over 60 years, Captain America is the living, breathing symbol of freedom and liberty.",
            "http://i.annihil.us/u/prod/marvel/i/mg/3/50/537ba56d31087.jpg"),
    )
}